@TmsApi_HostAddress = http://localhost:5123

GET {{TmsApi_HostAddress}}/weatherforecast/
Accept: application/json

###
@TmsApi_HostAddress = http://localhost:5123/api/enrollments/worker-smoke
GET {{TmsApi_HostAddress}}/api/assessments/resultsj