@TmsApi_HostAddress = http://localhost:5123

Accept: application/json

###
@TmsApi_HostAddress = http://localhost:5123
# GET {{TmsApi_HostAddress}}/api/enrollments/92d688e0

POST {{TmsApi_HostAddress}}/api/enrollments
Content-Type: application/json

{
    "studentId": "S-001",
    "courseCode": "CS-101"
}














































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































